### ISSUE TITLE
Issue with 2.0.0-beta.6 version

### ISSUE THREAD

**Issue by pruthvip** [dotansimha/angularjs-dropdown-multiselect#363] opened 2017-05-02 12:58 UTC
I am using 2.0.0-beta.6 version,(my angular version is < 1.5). But for some reason, instead of the label i provide , on the UI label is shown as `{{getPropertyForObject(option, settings.displayProp)}}`. Any idea what I am missing. I am using bootstrap > 3 also.

<img width="439" alt="screen shot 2017-05-02 at 6 29 02 pm" src="https://cloud.githubusercontent.com/assets/1709317/25618761/dbb9575e-2f65-11e7-9ae1-4e59de88f144.png">

the li has acess to the correct options. But while showing the text. Its not showing.

**Comment by pkempenaers** [comment] 2017-05-02 12:59
probably duplicate of #344

**Closed as completed by pkempenaers** 2017-05-02 12:59 UTC

**Comment by pruthvip** [comment] 2017-05-02 13:04
@pkempenaers I am  using 2.0.0-beta.6, which was supporting angular 1.2 and above.. even version 1 is also i tried. But still label is not coming
