### ISSUE TITLE
Hardcoded open close tags

### ISSUE THREAD

**Issue by Fossil01** [dotansimha/angularjs-dropdown-multiselect#313] opened 2017-03-10 09:14 UTC
You're using hardcoded {{ and }} tags. I am (and I'm sure many others) are using custom angular open/close tags so it won't interfere with my templating engine.

I have edited the .js to use my custom tags but it might be nice to have this in a variable somewhere.

**Comment by pkempenaers** [comment] 2017-03-10 09:18
Feel free to make a PR with the edited js

**Comment by Fossil01** [comment] 2017-03-10 09:23
I just edited the tags to match mine, no clue how to properly fix it. Sorry :)

**Comment by pkempenaers** [comment] 2017-03-19 19:58
duplicate of #282

**Closed by pkempenaers** 2017-03-19 19:58 UTC
